- hosts: localhost
  vars_files:
      - credential.yml
  tasks:
  - name: Configure Master Node on AWS cloud
    ec2:
          key_name: task
          instance_type: t2.micro
          image:  ami-0bcf5425cdc1d8a85
          wait: yes
          count: 1
          vpc_subnet_id: subnet-0b947660
          group_id: sg-42d06d38
          assign_public_ip: yes
          region: ap-south-1
          state: present
          group: default
          aws_access_key: "{{ accesskey }}"
          aws_secret_key: "{{ secretkey }}"
          instance_tags: {"Name": "Master", "Cluster": "k8s Cluster"}

- hosts: localhost
  vars_files:
      - credential.yml
  tasks:
  - name: Configure Worked Node on AWS cloud
    ec2:
          key_name: task
          instance_type: t2.micro
          image:  ami-0bcf5425cdc1d8a85
          wait: yes
          count: 2
          vpc_subnet_id: subnet-0b947660
          group_id: sg-42d06d38
          assign_public_ip: yes
          region: ap-south-1
          state: present
          group: default
          aws_access_key: "{{ accesskey }}"
          aws_secret_key: "{{ secretkey }}"
          instance_tags: {"Name": "Worker", "Cluster": "k8s Cluster"}
